# Generated by Django 3.2.7 on 2021-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
    ]
